# Generated by Django 5.0.6 on 2025-03-22 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleRatingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_distribution", models.JSONField(default=dict)),
                ("highest_rating", models.IntegerField(default=0)),
                ("lowest_rating", models.IntegerField(default=0)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article Rating Stats",
                "verbose_name_plural": "Article Rating Stats",
            },
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["article"], name="content_rat_article_79d321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["user"], name="content_rat_user_id_d6b87a_idx"),
        ),
        migrations.AddField(
            model_name="articleratingstats",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_stats",
                to="content.article",
            ),
        ),
    ]
