# Generated by Django 5.0.6 on 2025-03-24 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_articleratingstats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="content_art_created_4474c8_idx"
            ),
        ),
    ]
